apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubermatic-dl-deployment
spec:
  selector:
    matchLabels:
      app: kubermatic-dl
  template:
    metadata:
      labels:
        app: kubermatic-dl
    spec:
      containers:
      - name: kubermatic-dl
        image: kevinsteeven/imagenapi:v1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kubermatic-dl-service
spec:
  selector:
    app: kubermatic-dl
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
